import { BlockDefinition, BlockShape, BlockCategory } from './types';

export const BLOCK_CATALOG: Record<string, BlockDefinition> = {
  'cube_1x1x1': {
    id: 'cube_1x1x1',
    name: 'Cube 1x1x1',
    size: { x: 1, y: 1, z: 1 },
    shape: BlockShape.Box,
    maxHp: 100,
    mass: 1,
    color: '#ffcc00',
    category: BlockCategory.Basic,
  },
  'brick_2x1x1': {
    id: 'brick_2x1x1',
    name: 'Brick 2x1x1',
    size: { x: 2, y: 1, z: 1 },
    shape: BlockShape.Box,
    maxHp: 150,
    mass: 2,
    color: '#ff3300',
    category: BlockCategory.Basic,
  },
  'plate_2x2x0.25': {
    id: 'plate_2x2x0.25',
    name: 'Plate 2x2x0.25',
    size: { x: 2, y: 0.25, z: 2 },
    shape: BlockShape.Box,
    maxHp: 50,
    mass: 0.5,
    color: '#3366ff',
    category: BlockCategory.Basic,
  },
  'long_brick_4x1x1': {
    id: 'long_brick_4x1x1',
    name: 'Long Brick 4x1x1',
    size: { x: 4, y: 1, z: 1 },
    shape: BlockShape.Box,
    maxHp: 200,
    mass: 4,
    color: '#00cc66',
    category: BlockCategory.Basic,
  },
  'large_block_4x2x1': {
    id: 'large_block_4x2x1',
    name: 'Large Block 4x2x1',
    size: { x: 4, y: 2, z: 1 },
    shape: BlockShape.Box,
    maxHp: 300,
    mass: 8,
    color: '#9933ff',
    category: BlockCategory.Basic,
  },
  'wedge': {
    id: 'wedge',
    name: 'Wedge',
    size: { x: 1, y: 1, z: 1 },
    shape: BlockShape.Wedge,
    maxHp: 100,
    mass: 1,
    color: '#666666',
    category: BlockCategory.Basic,
  },
  'cylinder': {
    id: 'cylinder',
    name: 'Cylinder',
    size: { x: 1, y: 1, z: 1 },
    shape: BlockShape.Cylinder,
    maxHp: 100,
    mass: 1,
    color: '#cccccc',
    category: BlockCategory.Basic,
  },
  'wheel': {
    id: 'wheel',
    name: 'Wheel',
    size: { x: 1, y: 1, z: 0.5 },
    shape: BlockShape.Cylinder,
    maxHp: 80,
    mass: 2,
    color: '#111111',
    category: BlockCategory.Vehicle,
  },
  'seat': {
    id: 'seat',
    name: 'Seat',
    size: { x: 1, y: 1, z: 1 },
    shape: BlockShape.Box,
    maxHp: 100,
    mass: 2,
    color: '#33ccff',
    category: BlockCategory.Vehicle,
  },
  'engine': {
    id: 'engine',
    name: 'Engine',
    size: { x: 1, y: 1, z: 1 },
    shape: BlockShape.Box,
    maxHp: 150,
    mass: 10,
    color: '#ff6600',
    category: BlockCategory.Vehicle,
  },
  'wing': {
    id: 'wing',
    name: 'Wing',
    size: { x: 2, y: 0.1, z: 1 },
    shape: BlockShape.Box,
    maxHp: 50,
    mass: 1,
    color: '#ffffff',
    category: BlockCategory.Aircraft,
  },
  'small_gun_mount': {
    id: 'small_gun_mount',
    name: 'Small Gun Mount',
    size: { x: 0.5, y: 0.5, z: 1 },
    shape: BlockShape.Box,
    maxHp: 100,
    mass: 3,
    color: '#333333',
    category: BlockCategory.Weapon,
  },
};
